### ISSUE TITLE
Cache expiration timespans are using incorrect units when creating FreecurrencyClient

### ISSUE THREAD

**Issue by wearysky** [StefH/FreecurrencyAPI#5]
The two expiration timespans in FreecurrencyClient  are taking their respective options and generating timespans in seconds, as opposed to minutes or hours as specified in the options object.

For the life of me I couldn't figure out why my API quota kept going down after identical calls, then I checked the code and saw that the default cache expiry time for exchange rates was being set to 60 seconds instead of 60 minutes :)

**Comment by StefH** [comment]
@wearysky : good catch! Thank you.
